set -g default-terminal "tmux-256color"
# Allow true color support
set -ga terminal-overrides ",*:RGB"

set -gq allow-passthrough on
set -s focus-events on
set -sg escape-time 0
setw -g extended-keys on
set -g status-keys vi
setw -g mode-keys vi

# Theming and layout
set -g status-position top
set -g status-style "bg=default"
set -g status-justify "absolute-centre"
set -g status-left-length 0
set -g status-left "#[fg=#{@thm_fg} bold][#S] "
set -ga status-left "#{?client_prefix,#[fg=#f38ba8 bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#f9e2af bold]COPY ,#[fg=#a6e3a1 bold]NORMAL }}"
set -g status-right ""
set -g window-status-current-style "bg=default,fg=#b4befe,bold"
set -g pane-active-border-style "bg=default fg=#b4befe"

# Transparent tmux background
set -g window-style "bg=terminal"
set -g window-active-style "bg=terminal"

# Allow changing cursor shape
# set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Set new prefix (Alt+Space)
unbind C-b
set -g prefix M-Space
bind Space send-prefix

bind -n M-r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Copy mode
bind 'v' copy-mode

# Split windows
bind | split-window -hc "#{pane_current_path}"
bind "\\" split-window -fh -c "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# Session and Window Switcher
unbind s
bind s choose-tree -Z -s -f '#{&&:#{!=:#{session_name},opencode},#{!=:#{session_name},notes},#{!=:#{session_name},news},#{!=:#{session_name},music},#{!=:#{session_name},mail},#{!=:#{session_name},tasks}}'
unbind w
bind-key -r -T prefix w run-shell 'tmux choose-tree -Nwf"##{==:##{session_name},#{session_name}}"'

# Toggle Bar
bind-key -n M-b set -g status
